// src/packages/markdown-editor/vue/src/MarkdownViewer.vue
<script setup lang="ts">
import { Viewer as CoreViewer } from "@f-wiki/markdown-editor";
import type { ParserPlugin } from "@f-wiki/markdown-parser";
import { onMounted, onUnmounted, ref, watch } from "vue";

interface Props {
  content: string;
  plugins?: ParserPlugin[];
  urlFilter?: (url: string) => boolean;
  class?: string;
}

const props = defineProps<Props>();

const containerRef = ref<HTMLDivElement | null>(null);
let viewer: CoreViewer | null = null;

onMounted(() => {
  if (!containerRef.value) return;

  viewer = new CoreViewer(
    containerRef.value,
    props.plugins ?? [],
    props.urlFilter
  );
  viewer.render(props.content);
});

onUnmounted(() => {
  viewer?.destroy();
  viewer = null;
});

watch(
  () => props.content,
  (next) => {
    viewer?.render(next);
  }
);
</script>

<template>
  <div ref="containerRef" :class="props.class" />
</template>

// src/packages/markdown-editor/react/src/MarkdownViewer.tsx
import { Viewer as CoreViewer } from "@f-wiki/markdown-editor";
import type { ParserPlugin } from "@f-wiki/markdown-parser";
import { useEffect, useRef } from "react";

export interface MarkdownViewerProps {
  content: string;
  plugins?: ParserPlugin[];
  urlFilter?: (url: string) => boolean;
  className?: string;
}

export function MarkdownViewer({
  content,
  plugins,
  urlFilter,
  className,
}: MarkdownViewerProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const viewerRef = useRef<CoreViewer | null>(null);

  useEffect(() => {
    if (!containerRef.current) return;

    const viewer = new CoreViewer(
      containerRef.current,
      plugins ?? [],
      urlFilter,
    );
    viewerRef.current = viewer;
    viewer.render(content);

    return () => {
      viewer.destroy();
      viewerRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    viewerRef.current?.render(content);
  }, [content]);

  return <div ref={containerRef} className={className} />;
}
